[package]
name = "fmsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.1", features = ["sqlite"] }
dotenvy = "0.15.7"

[package.scripts]
schema = "diesel print-schema --database-url data/fm.db > src/schema.rs"