// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::prelude::*;
use crate::data::schema::*;

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(animation_id))]
pub struct AnimType {
    pub animation_id: i32,
    pub name: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(type_id))]
pub struct CardType {
    pub type_id: i32,
    pub name: String,
    pub is_monster: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(card_id))]
pub struct Card {
    pub card_id: i32,
    pub name: String,
    pub description: String,
    pub guardian_star_a_id: i32,
    pub guardian_star_b_id: i32,
    pub level: i32,
    pub type_id: i32,
    pub attack: i32,
    pub defense: i32,
    pub stars: i32,
    pub card_code: i32,
    pub attribute: i32,
    pub name_color: i32,
    pub desc_color: i32,
    pub abc_sort: i32,
    pub max_sort: i32,
    pub atk_sort: i32,
    pub def_sort: i32,
    pub typ_sort: i32,
    pub ai_sort: i32,
    pub ai_gs: Option<i32>,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(choice_id))]
pub struct ChoiceType {
    pub choice_id: i32,
    pub name: String,
    pub time_cost: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(decomp_id))]
pub struct Decomp {
    pub decomp_id: i32,
    pub animation_id: i32,
    pub choice_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(duelist_pool_id))]
pub struct DuelistPool {
    pub duelist_pool_id: i32,
    pub duelist_id: i32,
    pub pool_type_id: i32,
    pub card_id: i32,
    pub prob: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(duelist_id))]
pub struct Duelist {
    pub duelist_id: i32,
    pub name: String,
    pub is_mage: bool,
    pub hand_size: i32,
    pub low_lp_threshold: i32,
    pub critical_deck_size: i32,
    pub max_fusion_length: i32,
    pub max_improve_length: i32,
    pub spell_probability: String,
    pub attack_probability: String,
    pub find_best_combo_td: i32,
    pub improve_monster_td: i32,
    pub set_magic_td: i32,
    pub find_best_combo_no_td: i32,
    pub improve_monster_no_td: i32,
    pub set_magic_no_td: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(equip_id))]
pub struct Equip {
    pub equip_id: i32,
    pub equip_card_id: i32,
    pub card_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(field_effect_id))]
pub struct FieldEffect {
    pub field_effect_id: i32,
    pub field_type_id: i32,
    pub card_type_id: i32,
    pub relation: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(field_type_id))]
pub struct FieldType {
    pub field_type_id: i32,
    pub name: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(fixed_adv_id))]
pub struct FixedAdv {
    pub fixed_adv_id: i32,
    pub animation_id: i32,
    pub initial_seed_index: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(fusion_id))]
pub struct Fusion {
    pub fusion_id: i32,
    pub card1_id: i32,
    pub card2_id: i32,
    pub result_card_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(guardian_star_id))]
pub struct GuardianStar {
    pub guardian_star_id: i32,
    pub name: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(pool_type_id))]
pub struct PoolType {
    pub pool_type_id: i32,
    pub name: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(ritual_id))]
pub struct Ritual {
    pub ritual_id: i32,
    pub ritual_card_id: i32,
    pub card1_id: i32,
    pub card2_id: i32,
    pub card3_id: i32,
    pub result_card_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(pool_id))]
pub struct StarterGroup {
    pub pool_id: i32,
    pub sample_size: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(starter_pool_id))]
pub struct StarterPool {
    pub starter_pool_id: i32,
    pub pool_id: i32,
    pub card_id: i32,
    pub prob: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(variable_adv_id))]
pub struct VariableAdv {
    pub variable_adv_id: i32,
    pub animation_id: i32,
    pub initial_seed_index: i32,
    pub advance_size: i32,
}

